FROM openjdk:8-jdk-alpine
RUN mkdir -p /usr/local/MetaPeptideQuantome /usr/local/MetaPeptideQuantome/software
ADD @project.build.finalName@.jar /usr/local/MetaPeptideQuantome
ADD software /usr/local/MetaPeptideQuantome/software
